[package]
name = "lily-common"
description = "Shared types, errors and helpers used across Lily Protocol Soroban contracts"
keywords = ["lily-protocol", "soroban", "stellar", "blockchain"]
categories = ["cryptography::cryptocurrencies"]
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
rust-version.workspace = true
publish = false

[lib]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }

[lints]
workspace = true
